### ISSUE TITLE
The new modded alt tab is not recognising screen recording permissions for me

### ISSUE THREAD

**Issue by mal0121** [steventheworker/DockAltTab#25]
Hi Steven,

Again appreciate all the work you have done on this and the product you have created. Really useful.

The new modded alt tab just won't seem to recognise the permissions I have granted for it in regards to screen recording, it recognises accessibility has been granted but not screen recording. I have uninstalled everything and retried a few times and it just wont seem to work. I tried the normal alttab version to see if it was my laptop but it recognised everything fine. 

<img width="934" alt="image" src="https://github.com/steventheworker/DockAltTab/assets/119678155/13bcad5e-9cfb-4707-a0df-97282b4a22cf">

Im running M1, 12.6.1 Monterey 

Any suggestions appreciated :)

**Comment by steventheworker** [comment]
Close System Settings and quit AltTab (with Activity Monitor).
Use the below commands to forcefully forget permissions.
```tccutil reset All com.steventheworker.alt-tab-macos```
Now you can run AltTab and try adding the permissions again. Let me know if it works!

**Comment by mal0121** [comment]
Hi Steven,

Thanks for prompt reply. Have tried these but no cigar. The previous version of the build works fine so I'm unsure what is causing this.  Will just revert to that for now!

**Comment by spiritually-soup** [comment]
Hi Steven,

Chiming in as I have this issue too. I ran the terminal command fix as suggested but issue persists :(

Running Monterey 12.6.6 on an intel mac

<img width="1286" alt="SCR-20231004-mnok" src="https://github.com/steventheworker/DockAltTab/assets/92115028/29038fa1-9e09-4d89-bc26-e94645bfbd0a">

**Comment by steventheworker** [comment]
**Troubleshooting:**

1. Check if AltTab is running in Activity Monitor, quit/force quit those processes.
1. reset original AltTab permissions
```tccutil reset All com.lwouis.alt-tab-macos```
reset modded AltTab permissions
```tccutil reset All com.steventheworker.alt-tab-macos```
1. Verify no entries for AltTab exist under Accessibility and Screen Recording.
1. Make sure you only have one copy of AltTab on the filesystem. If you still have other copies (including the original AltTab), put them in the trash, then empty the trash.
      - try searching AltTab in spotlight and see if more than one comes up
1. Close/reopen Settings.
1. Locate the modded AltTab.app in finder
1. Re-add permissions:
     - You should be able to re-add the permissions by opening AltTab.app and following the prompts as you normally would...  
     - but to err on the side of caution, you can manually add the permissions BEFORE opening AltTab.app, by dragging AltTab.app into the list of entries under Accessibility & Screen Recording. (or using the + sign)

&nbsp;

<details>
  <summary>DockAltTab vs Dock Exposé</summary>

&nbsp;

DockAltTab can give you previews for the current space OR all spaces (and shows above dock icons). Since AltTab lets you customize the preview appearance (and size) it's more customizable.

&nbsp;

Dock Exposé opens app exposé (the command + down arrow menu), so the behavior is the same, taking up the whole screen w/ a bottom bar of recent files/folders, and can only show previews from every space. 
 
&nbsp;

</details>
