### ISSUE TITLE
Update Modded AltTab to match new AltTab release patches/fixes

### ISSUE THREAD

**Issue by sybercorp** [steventheworker/DockAltTab#3]
Please update your modded AltTab to be based on the newest release of the official AltTab that patches an issue with mouse events.

**Comment by steventheworker** [comment]
Done. [v6.46.1 Download](https://github.com/steventheworker/alt-tab-macos/releases/download/v6.46.1/DockAltTab.AltTab.v6.46.1.zip)

**Comment by sybercorp** [comment]
Thanks for the rapid response.  One question, though.  The modded AltTab checks for updates automatically by default.  Does this need to be disabled or did you modify it to look for the modded AltTab (making it safe to use the auto-update feature)?

**Comment by steventheworker** [comment]
Yeah AltTab seems to be compiled via CLI which updates the #VERSION# variable using the sparkle framework (which I unfortunately haven't gotten around to learning), so I would recommend disabling updates since those are currently linked to the official AltTab repository.

If you want to start DockAltTab on login, you will have to add it to System Preferences under "Login Items".
