### ISSUE TITLE
Multi monitor displays places the previews in the lower left of the screen

### ISSUE THREAD

**Issue by tdupont750** [steventheworker/DockAltTab#4]
Unfortunately the app is unusable when the previews are not right above the dock icons.  Not sure what additional information to provide.

**Comment by tdupont750** [comment]
I am also on an M1, but with Monterey 12.3.  I tried reinstalling but it still has the same problem.  Please let me know if there is any other information that I can provide.

**Comment by steventheworker** [comment]
1. Where are the previews showing from? The default AltTab location? Or somewhere else?
2. Make sure you have no other copies of DockAltTab and AltTab on the hard drive.
3. If this is from conflict with another app it could be helpful to know which other apps are running.
- paste this into the terminal to get a list of all running processes
   - osascript -e 'tell application "System Events" to return name of processes'
   - paste the output here, [here's mine](https://pastebin.com/uBdYJWLj) for comparison

**Comment by DavidKaub** [comment]
I guess I'm having the same issue. Never used either `AltTab` nor `DockAltTab` before. Just reinstalled again with the latest release and the 
> [scriptable AltTab (1.1)](https://github.com/steventheworker/alt-tab-macos/releases/download/1.1/DockAltTab.AltTab.v6.46.1.zip) 

AltTab verison you mentioned [above](https://github.com/steventheworker/DockAltTab/issues/4#issuecomment-1209705103)
For me, ad 1: Bottom left corner (see picture). This is not the AltTab location.
![Bildschirmfoto 2022-08-10 um 12 08 38](https://user-images.githubusercontent.com/45941163/183876090-71470cac-c923-4d0b-bda0-526e07c701a6.png)

ad 3:
Running `osascript -e 'tell application "System Events" to return name of processes'` yields:

```
loginwindow, ViewBridgeAuxiliary, SystemUIServer, ControlCenter, talagent, ViewBridgeAuxiliary, QuickLookUIService, Finder, NotificationCenter, Spotlight, OneDrive, Seafile FinderSync, AppSSOAgent, AirPlayUIAgent, TextInputMenuAgent, WiFiAgent, CoreServicesUIAgent, imklaunchagent, AutoLauncher, Rectangle, UnnaturalScrollWheels, Spotify, TextInputSwitcher, CoreLocationAgent, Keychain Circle Notification, OneDrive File Provider, SoftwareUpdateNotificationManager, Google Chrome, UIKitSystem, familycircled, coreautha, OSDUIHelper, Teams, Microsoft Outlook, Microsoft Teams Helper (Renderer), storeuid, com.apple.WebKit.Networking, com.apple.WebKit.WebContent, PowerChime, studentd, UserNotificationCenter, IsExtensionEnabled, Discord, universalAccessAuthWarn, ThumbnailExtension_macOS, TextEdit, Electron, KeePassXC, com.apple.appkit.xpc.openAndSavePanelService, QuickLookUIService, Seafile FinderSync, Docker, Docker Desktop, com.apple.appkit.xpc.openAndSavePanelService, QuickLookUIService, Seafile FinderSync, Seafile FinderSync, Seafile FinderSync, Seafile FinderSync, Seafile FinderSync, LookupViewService, AlDente, nbagent, System Preferences, AccountProfileRemoteViewService, com.apple.preference.security.remoteservice, AvatarPickerMemojiPicker, AdvertisingExtension, PrivacyPhotos, PrivacyAnalytics, LocalAuthenticationRemoteService, com.apple.appkit.xpc.openAndSavePanelService, QuickLookUIService, Seafile FinderSync, Dock, com.apple.dock.extra, DockHelper, Reminders, Preview, AltTab, DockAltTab, Terminal, System Events, osascript, FolderActionsDispatcher
```

**Comment by tdupont750** [comment]
osascript showed that i was only running one copy of AltTab, and it should have been the scriptable copy not running from Applications

**Comment by steventheworker** [comment]
So you have the official copy in applications? Because from experience, macOS will cache & run the first version you installed, unless you remove it. In the meantime, you could also use [DockAltTab v2.0](https://github.com/steventheworker/DockAltTab/releases/download/v2.0/DockAltTab-v2.0.zip) which places previews @ the default AltTab location.

**Comment by tdupont750** [comment]
I will try removing everything and reinstalling the scriptable version. Forgive me for being a novice Mac user, but any advice on how to ensure that any cached versions have been cleaned up?

**Comment by steventheworker** [comment]
Well since David is having the same issue and has never had either app installed prior, it could just be a software bug and not a caching issue.

But just in case, you can use spotlight to search the app and use command + enter to open it in Finder. If a copy exists, delete it and then empty the trash. Do that until there's no results in spotlight.

Do you happen to have an international keyboard or macOS set to another language? I thought I'd ask since that used to be an issue, and David had his set to German.

**Comment by tdupont750** [comment]
v2.0 worked just fine and placed the previews in the center middle of the screen

**Comment by DavidKaub** [comment]
I don't know why exactly, but it's working now for me. Things I changed.
1. Installed v2.0 which worked but as expected the previews ape rared in the middle of the screen
2. I removed most apps from the Accessibility settings and additionally removed 'Dock Window preview' (which I tried to use before for the exact same purpose but did not work) from the Mac (was listed in the Accessibility also). 
3.  Installed v2.2
4. After it seamed to work, I added all apps except 'Dock Window preview' to the Accessibility settings again, and it still worked.

I do not know if it now works because of the removed apps or because I used v2.0 before or because of any other reason, but I'm very happy with the result. Also, I realized that before, I might have installed an automated update of `AltTab` immediately after installation of the scripted version because the app suggested it to me.

One more thing I'd like to mention is that when I was able to "fix" the issue, i.e. I reinstalled both the apps etc. my Mac was not connected to an external display. I connected the Mac to the external display only after it worked on the internal - but it still works now!

I hope with these experiences, maybe also @tdupont750 can get it running - and thanks to you @steventheworker for the help!

**Comment by tdupont750** [comment]
Launching DockAltTab while the laptop was not connected to multiple monitors worked, and then after adding the monitors everything has continued to work.  Should this issue be closed out, or is it still a bug that it does not initialize correctly?

@DavidKaub Thank you for finding the solution!

@steventheworker This app is great, thank you for all of your hard work!

**Comment by steventheworker** [comment]
So very thankful you guys figured this out! I'm thinking of leaving this issue open so others can find it more easily, since I can't figure out how to reproduce this without reinstalling macOS / buying a whole new laptop. 🤔

**Comment by DOCaCola** [comment]
The issue persists for me with or without the recommended settings. While i have external monitors connected occasionally, i have tried starting this with no monitors attached or even restarting the whole mac with no success.

**Comment by steventheworker** [comment]
To make sure your scriptable AltTab is working correctly, open the Notes app, and run these 3 commands in a terminal:
1. Show @ default AltTab position (centered)
- ``osascript -e 'tell application "AltTab" to showApp appBID "com.apple.Notes"'``
2. Show @ bottom left
- ``osascript -e 'tell application "AltTab" to showApp appBID "com.apple.Notes" x 0 y 0'``
3. Show @ 100px from bottom, 100px from left
- ``osascript -e 'tell application "AltTab" to showApp appBID "com.apple.Notes" x 100 y 100'``

If these commands don't work, you might have a copy of the official app that's running instead, or the permissions are wrong.

**Comment by DOCaCola** [comment]
These commands work just fine in my case. The AltTap preview also appears at the given offset.

**Comment by steventheworker** [comment]
When you hover over dock icons are there no previews at all? Or does it also show at the bottom left like it did for tdupont750 and DavidKaub?

**Comment by DOCaCola** [comment]
Sorry. I should have been clearer. Yes, the previews appear in the bottom left corner when i hover dock items.
<img width="1512" alt="Bildschirmfoto 2022-08-27 um 13 29 44" src="https://user-images.githubusercontent.com/2077396/187028249-f4223453-d46f-439c-b745-a9b85121229e.png">

**Comment by steventheworker** [comment]
Well since they both saw success after using [v2.0](https://github.com/steventheworker/DockAltTab/releases/download/v2.0/DockAltTab-v2.0.zip) to center the previews, could you try installing it, and then reinstalling [v2.2](https://github.com/steventheworker/DockAltTab/releases/download/v2.2/DockAltTab-v2.2.zip).

**Comment by DOCaCola** [comment]
With v2.0 the previews are indeed centered on the screen. When i then upgrade to v2.2 the previews are in the bottom left corner again.

**Comment by steventheworker** [comment]
Well DockAltTab uses Accessibility to get monitor sizes (as well as mouse coordinates), but since you're getting previews at all, that tells me that Accessibility shouldn't be the issue, but my gut is telling me it's only half working.

Quit the app and you can use `tccutil reset All com.steventheworker.DockAltTab` to remove all permission entries. Restart, and then try installing one last time. If it still won't work, you can continue using v2.0 until there's an update. Out of ideas for the moment 🫤

**Comment by DOCaCola** [comment]
Still no luck. Permissions are set correctly, but 2.2 still doesn't work. 2.0 is still working for some reason. I also tried deleting the preference files and caches.

**Comment by steventheworker** [comment]
Wait, so, does 2.1 place the previews in the correct position, or is it placed on bottom-left / centered?

**Comment by DOCaCola** [comment]
Actually, now v2.2 works as well. I do not know what exactly has changed. After downgrading to v2.0 (again), then going to v2.1 and then v2.2 for some reason the previews are in the correct position now.

**Comment by steventheworker** [comment]
Ha well that's great to hear. I'm still unsure if this bug was introduced between v2.0-v2.1, or v2.1-v2.2. Could also be that monitor sizes weren't being read consistently in all versions, but it's only noticeable in the last two versions (since those variables are finally being used).

**Comment by cetemadi** [comment]
I've tried the steps above on single an dual monitor setup and issue is still there. Went from version 2.0-2.4

**Comment by steventheworker** [comment]
I just made this a [troubleshoot channel](https://discord.gg/6mkEtnhafB) on discord to keep from repeating too many comments on this thread.
